version: '3.4'

services:
  api:
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./logs:/app/logs
      - ./client/public/images:/app/client/public/images
      - ./api/uploads:/app/api/uploads

  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
    logging:
      driver: "none"

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0.1
    restart: always
    ports:
      - 7700:7700
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data:/meili_data

  rag_api:
    container_name: LibreChat-RAG-API
    ports:
      - "8000:8000"
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    environment:
      - DB_HOST=pgvector
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - pgvector
    volumes:
      - rag-uploads:/app/uploads

  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  rag-uploads:
